# Generated by Django 4.0 on 2022-08-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=100)),
                ('meeting_date', models.DateField()),
                ('meeting_time', models.TimeField()),
                ('meeting_location', models.CharField(max_length=100)),
                ('meeting_description', models.TextField()),
                ('meeting_status', models.BooleanField(default=True)),
                ('meeting_created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
