# Generated by Django 4.0 on 2022-08-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_meetings_meeting_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='meetings',
            name='agendas',
            field=models.ManyToManyField(blank=True, to='meeting.Agendas'),
        ),
    ]
